name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish flutter_quill
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1

      - name: Publish flutter_quill_extensions
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
        with:
          working-directory: ./flutter_quill_extensions

      - name: Publish flutter_quill_test
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
        with:
          working-directory: ./flutter_quill_test

      - name: Publish quill_html_converter
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
        with:
          working-directory: ./packages/quill_html_converter
